### PR TITLE
Fix code to work with Fugue 0.8.7

### PR DESCRIPTION
**Pull request by goodwanghan**

### CODE REVIEW

File: datacompy/fugue.py [hunk 1]
```diff
@@ -577,8 +578,28 @@ def _deserialize(
         arr = [pickle.loads(r["data"]) for r in df if r["left"] == left]
         if len(arr) > 0:
             return pd.concat(arr).sort_values(schema.names).reset_index(drop=True)
-        return pd.DataFrame(
-            {k: pd.Series(dtype=v) for k, v in schema.pandas_dtype.items()}
+        # The following is how to construct an empty pandas dataframe with
```
Comment (goodwanghan) [inline datacompy/fugue.py:581]: This is the change to make fugue 0.8.6 compatible

File: datacompy/fugue.py [hunk 2]
```diff
@@ -541,6 +541,7 @@ def _distributed_compare(
 
     def _serialize(dfs: Iterable[pd.DataFrame], left: bool) -> Iterable[Dict[str, Any]]:
         for df in dfs:
+            df = df.convert_dtypes()
```
Comment (goodwanghan) [inline datacompy/fugue.py:544]: This is the change to make fugue 0.8.7+ compatible

**Comment by goodwanghan** [comment]
@fdosani this change will make datacompy wotk with both the latest fugue and the lower versions.

**Comment by fdosani** [comment]
> @fdosani this change will make datacompy wotk with both the latest fugue and the lower versions.

Thank you! Taking a look through the PR now.

**Comment by fdosani** [comment]
@goodwanghan I'm having some issues when I was testing with `"fugue==0.8.6"` explicitly.
When I run `pytest tests/test_fugue.py`:

```
============================================================ short test summary info =============================================================
FAILED tests/test_fugue.py::test_is_match_native - AttributeError: 'PandasUtils' object has no attribute 'enforce_type'
FAILED tests/test_fugue.py::test_is_match_spark - pyspark.errors.exceptions.captured.PythonException:
FAILED tests/test_fugue.py::test_is_match_polars - AttributeError: 'PandasUtils' object has no attribute 'enforce_type'
FAILED tests/test_fugue.py::test_is_match_duckdb - AttributeError: 'PandasUtils' object has no attribute 'enforce_type'
FAILED tests/test_fugue.py::test_doc_case - AttributeError: 'PandasUtils' object has no attribute 'enforce_type'
FAILED tests/test_fugue.py::test_report_pandas - AttributeError: 'PandasUtils' object has no attribute 'enforce_type'
FAILED tests/test_fugue.py::test_report_spark - pyspark.errors.exceptions.captured.PythonException:
================================================== 7 failed, 12 passed, 127 warnings in 32.60s ===================================================
```

Specifically seems to be maybe some incompatibility with Pandas dataframe conversion:
```
   def as_pandas(self) -> pd.DataFrame:
        """Convert to pandas DataFrame"""
        pdf = pd.DataFrame(self.as_array(), columns=self.columns)
        if len(pdf) == 0:  # TODO: move to triad
            return pd.DataFrame(
                {
                    k: pd.Series(dtype=v.type.to_pandas_dtype())
                    for k, v in self.schema.items()
                }
            )
>       return PD_UTILS.enforce_type(pdf, self.schema.pa_schema, null_safe=True)
E       AttributeError: 'PandasUtils' object has no attribute 'enforce_type'

../../../miniconda3/envs/datacompy/lib/python3.10/site-packages/fugue/dataframe/dataframe.py:123: AttributeError
```

Fugue 0.8.7 works prefectly fine since the GitHub Actions tests all seem to pass just fine.
Is this a mismatch with Triad maybe since the `PandasUtils` is coming from there?

**Comment by goodwanghan** [comment]
> @goodwanghan I'm having some issues when I was testing with `"fugue==0.8.6"` explicitly. When I run `pytest tests/test_fugue.py`:
> 
> ```
> ============================================================ short test summary info =============================================================
> FAILED tests/test_fugue.py::test_is_match_native - AttributeError: 'PandasUtils' object has no attribute 'enforce_type'
> FAILED tests/test_fugue.py::test_is_match_spark - pyspark.errors.exceptions.captured.PythonException:
> FAILED tests/test_fugue.py::test_is_match_polars - AttributeError: 'PandasUtils' object has no attribute 'enforce_type'
> FAILED tests/test_fugue.py::test_is_match_duckdb - AttributeError: 'PandasUtils' object has no attribute 'enforce_type'
> FAILED tests/test_fugue.py::test_doc_case - AttributeError: 'PandasUtils' object has no attribute 'enforce_type'
> FAILED tests/test_fugue.py::test_report_pandas - AttributeError: 'PandasUtils' object has no attribute 'enforce_type'
> FAILED tests/test_fugue.py::test_report_spark - pyspark.errors.exceptions.captured.PythonException:
> ================================================== 7 failed, 12 passed, 127 warnings in 32.60s ===================================================
> ```
> 
> Specifically seems to be maybe some incompatibility with Pandas dataframe conversion:
> 
> ```
>    def as_pandas(self) -> pd.DataFrame:
>         """Convert to pandas DataFrame"""
>         pdf = pd.DataFrame(self.as_array(), columns=self.columns)
>         if len(pdf) == 0:  # TODO: move to triad
>             return pd.DataFrame(
>                 {
>                     k: pd.Series(dtype=v.type.to_pandas_dtype())
>                     for k, v in self.schema.items()
>                 }
>             )
> >       return PD_UTILS.enforce_type(pdf, self.schema.pa_schema, null_safe=True)
> E       AttributeError: 'PandasUtils' object has no attribute 'enforce_type'
> 
> ../../../miniconda3/envs/datacompy/lib/python3.10/site-packages/fugue/dataframe/dataframe.py:123: AttributeError
> ```
> 
> Fugue 0.8.7 works prefectly fine since the GitHub Actions tests all seem to pass just fine. Is this a mismatch with Triad maybe since the `PandasUtils` is coming from there?
> 
> EDIT: confirmed If I downgrade to `triad==0.9.1` the tests are passing. Maybe we can just put fugue at `0.8.7`:
> 
> ```
> dependencies = [
>     "pandas<=2.0.2,>=0.25.0",
>     "numpy<=1.26.0,>=1.22.0",
>     "ordered-set<=4.1.0,>=4.0.2",
>     "fugue<=0.8.7,>=0.8.7",
> ]
> ```

Yes, because 0.8.6 didn't have a cap on Triad, and triad 0.9.3 no longer works with Fugue 0.8.6-.

So if people pinned the versions, they should have Fugue 0.8.6 with triad 0.9.2 but if they let the versions to be flexible, both will update to the latest versions so there shouldn't be problem. Only when you manually set triad to be 0.9.3 and Fugue to be 0.8.6- there can be compatibility issues

**Comment by goodwanghan** [comment]
And yes we can just update fugue requirement to 0.8.7

File: pyproject.toml [hunk 3]
```diff
@@ -15,7 +15,7 @@ dependencies = [
     "pandas<=2.0.2,>=0.25.0",
     "numpy<=1.26.0,>=1.22.0",
     "ordered-set<=4.1.0,>=4.0.2",
-    "fugue<=0.9.0,>=0.8.6",
+    "fugue<0.9.0,>=0.8.6",
```
Comment (fdosani) [inline pyproject.toml:18]:
```suggestion
"fugue<=0.8.7,>=0.8.7",
```

**Review by fdosani — COMMENTED** [review]
Just one change (made a suggestion). For context I set it as: `"fugue<=0.8.7,>=0.8.7",` because we use [edgetest](https://github.com/capitalone/edgetest) which runs once a week and will bump up versions as they pass and become available. It is automatically done via actions.

**Comment by goodwanghan** [comment]
@fdosani i think this is good to merge

**Review by fdosani — APPROVED** [review]

**Comment by fdosani** [comment]
@goodwanghan thank you again for your help!

**Comment by goodwanghan** [comment]
Thank you so much @fdosani  and I apologize for the inconvenience.
